### ISSUE TITLE
Unable to install wggithub

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#20]
Unable to install wggithub. Error(s):
Installing wgGitHub
Failed to execute xoops_module_pre_install_wggithub

This module requires XOOPS 2.5.11+ (2.5.11-Beta1 installed)

XOOPS Version | XOOPS 2.5.11-Beta1
-- | --
PHP Version | 7.4.4
mySQL Version | 8.0.16

**Comment by alain01** [comment]
Unable to install wggithub. Error(s):
Installing wgGitHub
Failed to execute xoops_module_pre_install_wggithub

This module requires XOOPS 2.5.11+ (2.5.11-Beta2 installed)

XOOPS Version | XOOPS 2.5.11-Beta2
-- | --
PHP Version | 7.4.4
MySQL Version | 8.0.16

**Comment by ggoffy** [comment]
hi

does it work if you remove 
`declare(strict_types=1);`
from class/Common/VersionChecks.php

**Comment by alain01** [comment]
Humm
line ?
Dont find it in the class/Common/VersionChecks.php file in your module

**Comment by ggoffy** [comment]
hi. please test last version

**Comment by ggoffy** [comment]
see also https://github.com/XOOPS/XoopsCore25/issues/966

**Comment by alain01** [comment]
Ok, so I will wait for your PR in the XOOPS core ?
I didnt test again with your new version

**Comment by ggoffy** [comment]
last version of wggithub fix the problem for install procedure

**Comment by alain01** [comment]
Ok, @ggoffy 
Now i can install it with your latest version but i get the message here but I think it's not important.
![Capture d’écran 2021-03-09 215206](https://user-images.githubusercontent.com/5336960/110536428-becde300-8121-11eb-845a-1120314ff42d.png)

**Comment by ggoffy** [comment]
yes, this is from core/modulesadmin which should bem fixed with XOOPS/XoopsCore25#966
but it doesnt has an effect on wggithub :)
