### ISSUE TITLE
Error : RuntimeException: "Error exchange data with GitHub: file not found"

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#22]
Hello
if I add a wrong name or unknown name from github on the directories tab, I get this error when I go to the /modules/wggithub/ page.

Ok, I know that it's stupid to add a wrong name but I think we should get an alert message (cleaner)

Let me know If you think my tests are stupid, please.

**Comment by alain01** [comment]
Hum, ok for the message but we get a pseudo blank page

**Comment by ggoffy** [comment]
this is an error which can only occur if you are setting up the module. Once the directories are saved in proper way this error will not occur any more

**Comment by ggoffy** [comment]
I will check it :)

**Comment by ggoffy** [comment]
you have a blank page? you should have this:
![grafik](https://user-images.githubusercontent.com/7547661/110844736-1008de80-82aa-11eb-9855-f2e0e3946634.png)

**Comment by alain01** [comment]
not a blank page, a pseudo blank page ;-)
Yes, This page !

**Comment by alain01** [comment]
but the message is 
"Error : RuntimeException: "Error exchange data with GitHub: file not found"
;-)

**Comment by ggoffy** [comment]
implemented

**Comment by alain01** [comment]
![Capture d’écran 2021-03-18 140204](https://user-images.githubusercontent.com/5336960/111630354-91a0c500-87f2-11eb-83c1-96dd8748a734.png)
This ? 
Ok, 
I thought you display an alert like "This repository does not exist" 
but it's ok for me, much better than before.

**Comment by ggoffy** [comment]
yes, this :)

you can change in language/main.php 
`\define('_MA_WGGITHUB_READGH_ERROR_API_404', 'Error exchange data with GitHub: file not found');`
into
`\define('_MA_WGGITHUB_READGH_ERROR_API_404', 'Error exchange data with GitHub: This repository does not exist');`

:)

I selected "file not found" because this is the http 404 status code :)

**Comment by alain01** [comment]
Ok Thank you Goffy !
