### ISSUE TITLE
Suggestion : Filter Release option

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#23]
Back office : 
option to choose Filter Release:

- Only Final
- Final + Release
- All

Why : 
For frontfoffice side, users are novices, and I prefer show just "Only Final" or "Final + Release"

**Comment by ggoffy** [comment]
the preselection on user side will be made on your settings for the directory.
do you want to exclude non-released completely?

**Comment by alain01** [comment]
Yes, for the lambda users.
They dont know the difference between Final, RC, master.
Often click clik click

**Comment by ggoffy** [comment]
but then you accept, that a experienced user will even not see this non-released modules

**Comment by alain01** [comment]
OK, I think an experienced user visits directly the github site, no ?

**Comment by ggoffy** [comment]
maybe, my intention was to give a short overview of all ;)
but of course if you say you want to make a tailor made view, it is also ok :)

**Comment by ggoffy** [comment]
please test last version from https://github.com/ggoffy/wggithub

**Comment by alain01** [comment]
Ok, so I need to check your code with bt4 template cause you add some smarty variable to display or not filter (no present in my bt4 template). I will checked to modify when it will be stable.

For the standard tpl,
The "Apply Filter Release" is ok in the backoffice side (when i choose a mode like "all" , the filter is ok on frontoffice page)

But strange comportement on click, frontoffice side. 
When I click on filter, filter works (the results) but filter disappear

Hum,
if no filter, i get the 180 repo for XOOPSModules25x
I thought i should get 34 modules (only final, no ?)

Cosmetic remark : 
sort for Apply Filter Release : 
"1 - Do not show filter"
"2 - use filter release only"
"3 - use filter all"
 
We should use a prefix (1,2,3 or A, B,C) cause languages...

**Comment by ggoffy** [comment]
`When I click on filter, filter works (the results) but filter disappear`
fixed

`sort for Apply Filter Release`
fixed

`We should use a prefix (1,2,3 or A, B,C) cause languages`
I dont think so, because then I would have to do the same in all lists ;)

`bt4 template`
are your templates also working with a bt3 theme? if yes, I would switch completely to bt4

**Comment by alain01** [comment]
Templates : 

No, that's why I worked totransform the index template (bt3) in bt4 in the xswatch4 theme.
With a bt4 theme (for example xswatch4), your templates (bt3) dont display tabs for directories and repositories.


### Your template (bt3) in a bt4 theme: 
![Capture d’écran 2021-03-12 084933](https://user-images.githubusercontent.com/5336960/110909951-fc449300-8310-11eb-8077-b4ae20263067.png)


### New bt4 template in a bt4 theme:
![Capture d’écran 2021-03-12 085033](https://user-images.githubusercontent.com/5336960/110910023-17170780-8311-11eb-8ef9-e88b09b3f07a.png)


### New bt4 template in a bt3 theme:
![Capture d’écran 2021-03-12 085705](https://user-images.githubusercontent.com/5336960/110910069-26965080-8311-11eb-91da-546bc0270e85.png)

**Comment by ggoffy** [comment]
shit, so we have to keep both in and adapting always both :(

**Comment by alain01** [comment]
lol and Bootstrap is closed to open a new version 5.0 stable (Now 5.0.0-beta2)

**Comment by alain01** [comment]
Got an error ! 

Process : 
Directories / Apply filter release : Use filter release only  
Then on front end : 
### OK : i see "Only Final" + "Any release"
![Capture d’écran 2021-03-16 005513](https://user-images.githubusercontent.com/5336960/111236143-7c5d4800-85f2-11eb-9e5e-2f08cf2ebb5c.png)

### But when I clicked on  "Only final", I get the 3th filter "All"
![Capture d’écran 2021-03-16 005624](https://user-images.githubusercontent.com/5336960/111236150-7f583880-85f2-11eb-9035-294e71389dbe.png)

**Comment by ggoffy** [comment]
hi. setting different options especially if it is different from directory to directory causes a lot if troubles.
is it ok for you if we use a general setting? Only releases for all directories or all (not released included) for all directories?

**Comment by alain01** [comment]
Hi,
It's your module.

My first goal is to not display 170 modules, or even 32, just a very quality selection.
So, I need to use "approuval" column.
And sure, we can use same filter for all directories, [release] and [All].

For [release], you mean Final + any release in the same group "release", yes ?
If yes, ok for me.

**Comment by ggoffy** [comment]
ok, then I will move the option from directory level to module preferences level :)

**Comment by ggoffy** [comment]
moved now to preferences. if you are testing dont forget to run module update

**Comment by alain01** [comment]
Filter : Final / RC

When i click on filter, (not full), both are selected so it's not ok ! 
![Capture d’écran 2021-03-16 225813](https://user-images.githubusercontent.com/5336960/111385825-a1fa5800-86ab-11eb-9c53-31cb1c95e1ec.png)
![Capture d’écran 2021-03-16 225918](https://user-images.githubusercontent.com/5336960/111385842-a6267580-86ab-11eb-8cf8-9a129d7b2e65.png)

**Comment by ggoffy** [comment]
ok, I will check

**Comment by ggoffy** [comment]
there was a bug in js. hope it works now for you

**Comment by alain01** [comment]
ok, fine Now ! 
I dont close this issue cause I want to check other thing, linked to the filters ;-)

**Comment by alain01** [comment]
I need to build again the bt4 templates in the /extra directory cause you used new smarty now.
So just wait 1 or 2 days please

**Comment by ggoffy** [comment]
ok, take your time :)

**Comment by alain01** [comment]
Yes, sorry, I should close it.
All is ok at the moment ! ;-)
