### ISSUE TITLE
Suggestion : Add Filter on backoffice on the repositories tab

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#24]
There are lot of repositories in the repositories tab cause XOOSModules 25 is very big

I want to see only GregMage repositories (So just display GregMage directories) in this page.
Filter can help.
Like that (module xmsocial)
![Capture d’écran 2021-03-10 094404](https://user-images.githubusercontent.com/5336960/110601420-33863900-8185-11eb-8091-db8a5c954084.png)

**Comment by alain01** [comment]
And why not same filter in the Readmes tab page and Releases tab page ?

**Comment by alain01** [comment]
No, just to help to find some repository in a big list.
May be filter by repository name :
tad* to display all tad repository
wg* for your modules...

Repositories tab in the backoffice

**Comment by ggoffy** [comment]
filters included

please test last version form https://github.com/ggoffy/wggithub

**Comment by alain01** [comment]
Argg, 
I've just tested 10 mn ago.
ok, re-donwload

**Comment by alain01** [comment]
ok ! TY
remarques : 
- by default : contain (not =)
- if filter give no result,  the alert is diplay during 5 seconds, ok, but then page is empty (no repository displayed)

**Comment by alain01** [comment]
Add the status filter please.

I use this field to not display some repositories on front office even it's a final version.("None" or "offline", same)
Is it the good way for that ?
I dont want to display the 34 x2.5 modules

**Comment by ggoffy** [comment]
`Add the status filter please`
done

`by default`
done

**Comment by ggoffy** [comment]
the filter for front end I will implement separately (this evening)

**Comment by alain01** [comment]
by default : name : **TX**
by default : contain (not =) : **TX**
Add the status filter : **TX**  Cool

Just a question : 
If I modify a status repository to "none"  there is no "none" on this news filter.
May be the status "none" is a non-sense ? (it's an informatique problem cause single-choice drop-down list?)
Help me to understand please

Filter front end (Ok, not frontOffice, i know now, TY ;-)) : I'm on the "starting block" to test ;-)

**Comment by ggoffy** [comment]
I have added now 
![grafik](https://user-images.githubusercontent.com/7547661/110943198-39257f80-833b-11eb-8e4d-bc2e58e0a6f3.png)

if you say "no" then you have to approve each repository manually on admin side
![grafik](https://user-images.githubusercontent.com/7547661/110943401-74c04980-833b-11eb-9130-111a97f2142b.png)
otherwise it will be not shown on user side

**Comment by alain01** [comment]
Perfect ! 
I will test ! 
And what is happen if I update the directory ?
All my selections as "approuved" stay as "approuved" or i need to restart all ?

**Comment by ggoffy** [comment]
should stay. let me know if not

**Comment by alain01** [comment]
This option is very vrey usefull, exactly what i wanted ! 
Thank you.
There are some little things to modify to be more efficient,
But I will explained when i could read github directory #28

**Comment by alain01** [comment]
> There are some little things to modify to be more efficient,

ok,  I will explain in an another issue! 
For this issue, filter is ok ! 
Thanks
