### ISSUE TITLE
Bug with long list of repositories

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#26]
To reproduce it, please try this : 

- On front office, choose Directory XoopsModules25x
- click on bottom list on the "...' link to diplay next repositories
- Again (3 times)

Ok, now you are on the last page of the repositories list
Now, change to another directory, for example "GregMage"
You get the "..." link, not the n first repositories on tab pane

;-)

**Comment by ggoffy** [comment]
fixed
please test

**Comment by alain01** [comment]
Hum 
Now, it's ok on the last page to change Directory

But

Another problem is coming
Sorry, I know I'm harsh with you, and may be it's a complex test, challenge may be. 
See capture to understand : 

### The before last page (not ok but not a problem, there is content)
![Capture d’écran 2021-03-12 125430](https://user-images.githubusercontent.com/5336960/110937346-8b15d780-8332-11eb-8359-493903489a25.png)

### So the very last page is not ok (no content) : 
![Capture d’écran 2021-03-12 125506](https://user-images.githubusercontent.com/5336960/110937563-d3cd9080-8332-11eb-9c33-d433185086df.png)

**Comment by ggoffy** [comment]
i made again some changes. in my current version I do not have this problem

**Comment by alain01** [comment]
Ok I will test tonight

**Comment by alain01** [comment]
Ok now ! Thanks

**Comment by ggoffy** [comment]
Thank you
