### ISSUE TITLE
Cant read directory from github with good token

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#28]
Hi,
Now i cant read directory from github.

I didnt use sample data
- I've added  a new setting (alain01, taken like that) :
![image](https://user-images.githubusercontent.com/5336960/110947361-56108180-8340-11eb-9971-41248f1b5465.png)

Then I've added a directory
XoopsModules25x / organisation/all forks

Then, "Read this directory from github"

Errors
--
Error: Error: Class 'XoopsModules/Wggithub/Github/Http/BadResponseException' not found in file /modules/wggithub/class/Github/Http/CurlClient.php line 110
Error : Error: Class 'XoopsModules\Wggithub\Github\Http\BadResponseException' not found

Same with sample data
with my token to "Read this directory from github"

Strange, it worked yesterday with my account

**Comment by ggoffy** [comment]
yes, strange, because I didn't change something in this part. seems to be a problem with http, not with wggithub.

**Comment by alain01** [comment]
So i cant update your sample datas
or add data from github in the empty module

**Comment by ggoffy** [comment]
strange, now I have the same error. I have to test it

**Comment by alain01** [comment]
Internal code or excessive requests with the gihthub API on github server ? 
Should they blocked requests ?

It's just my 1 cent idea !

**Comment by ggoffy** [comment]
Hi Alain
Richard found the problem, the certificate wasn't valid anymore (https://github.com/milo/github-api/issues/32)

can you please test current version from https://github.com/ggoffy/wggithub

**Comment by alain01** [comment]
Error: Error: Call to undefined function XoopsModules/Wggithub/MDParser/substr_/count() in file /modules/wggithub/class/MDParser/Parsedown.php line 781

**Comment by alain01** [comment]
I used my last api code and I check with your function 

> Github/GithubClient testApi1 (reading github public repos) successfully finished

Directories : "Read this directory from GitHub"
Loading data from GitHub successfully finished (GregMage, for example)
But get error with "go to module"

**Comment by alain01** [comment]
The released (on admin page) is ok, I can see the repositories from GregMage
The repositories (on admin page) are ok too (from GregMage)

Readmes tab : same trouble : Error: Error: Call to undefined function XoopsModules/Wggithub/MDParser/substr_/count() in file /modules/wggithub/class/MDParser/Parsedown.php line 781

**Comment by ggoffy** [comment]
error "substr_/count()" fixed. I think the error "go to module" is also fixed

**Comment by alain01** [comment]
Haa, better ;-)
Thank you
