### ISSUE TITLE
Permissions by default

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#29]
Global permissions
Set global permissions global for different groups

All is empty.

I think it is not important for the "Webmasters" group because the group has all the rights by default.
But it's better to check the boxes 
Permissions to view | Permissions to read new data from GitHub | Permissions to update existing readme with data from GitHub
-- | -- | --

**Comment by ggoffy** [comment]
hi. the rendering of the permission form is made by core, not by module

**Comment by alain01** [comment]
I know but I think you can predefine value for the group webmasters, no ?
IN another modules, it 's predifined. No ? 
Let me check with xmodules for examples

**Comment by alain01** [comment]
And Hi ! (sorry) like a chat conversation, ;-)

**Comment by alain01** [comment]
Ok, so I should close this issue ?
Let me know.

**Comment by ggoffy** [comment]
for me this is currently not "top priority" ;)

i close it
