### ISSUE TITLE
Error : Error: Class 'XoopsModules\Wggithub\Constants' not found

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#30]
Hi,

I dont know if it's a mistake by me or not,
but with the last version, when I want to install the module, (button "Install module")
http://xoops-tests2.local/modules/system/admin.php?fct=modulesadmin&op=installlist

I get this error : 

Error : Error: Class 'XoopsModules\Wggithub\Constants' not found.

If I delete the /modules/wggithub directory, I can install other modules

**Comment by alain01** [comment]
XOOPS Version | XOOPS 2.5.11-Beta2
-- | --
PHP Version | 7.4.4
MySQL Version | 8.0.16

**Comment by ggoffy** [comment]
no, it's not your fault, it's mine

fixed

**Comment by alain01** [comment]
Ok, fixed !

**Comment by ggoffy** [comment]
thank you
