### ISSUE TITLE
Question : tabs order

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#32]
Hi,
just a question: 

The tabs order is set for a way to use your module or no ?

With my way to use your module, I dont use tab "Logs" and "Readmes"
I used Directories / Repositories / Releases  and settings (but just 1 time, to add my API)

So my question is why the log tab in the 4th place, not at the end, just before feedback

And what can I do with the readmes tab ?
If I'm owner, I can write readme since your module and put it on gihtub ?

**Comment by ggoffy** [comment]
the order is more "historical" grown, not related to the use. if you wish I can change it :)

`If I'm owner, I can write readme since your module and put it on gihtub ?`
no, this module is only for download and show it to your users

my intention was always to give our (new) visitors of website a quick overview of the possibilities of XOOPS, this module is not a tool for developers 

I think I will remove also the "Add..." buttons

**Comment by alain01** [comment]
> the order is more "historical" grown, not related to the use. if you wish I can change it :)
COOOOOooooollllll ;-)

IMO
Dashboard / Directories / Repositories / Releases / Settings / Permissions / (Logs) / (Readmes) / Feedback / about / Help


> I think I will remove also the "Add..." buttons
In the Readmes tab ? sure so

**Comment by ggoffy** [comment]
I made now following sorting for tabs:
first the ones where you have to make something

- Settings
- Directories
- Permissions

then the other ones where you see what is in the database

- Repositories
- Releases
- Readmes
- Logs

**Comment by alain01** [comment]
ok !

**Comment by ggoffy** [comment]
thank you

**Comment by alain01** [comment]
Error,
Repositories


Readmes


Releases
Logs

;-)

**Comment by ggoffy** [comment]
?????

**Comment by alain01** [comment]
You write : 
Repositories
Releases
Readmes
Logs

but it's 

Repositories
Readmes
Releases
Logs

**Comment by ggoffy** [comment]
ah, ok

**Comment by alain01** [comment]
I am merciless ;-))))

**Comment by ggoffy** [comment]
its always good to have someone who is checking in details ;)

**Comment by ggoffy** [comment]
please continue

**Comment by alain01** [comment]
Reopen this issue cause bad order.
We want:

1. Repositories
2. Releases
3. Readmes
4. Logs

but it's

1. Repositories
2. **Readmes**
3. Releases
4. Logs

**Comment by alain01** [comment]
Tested from ggoffy/wggithub, not from XoopsModules25x/wggithub

**Comment by ggoffy** [comment]
done :)

**Comment by alain01** [comment]
Ok now, Cool ! Thank you !
