### ISSUE TITLE
Forced Settings and Token

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/wggithub#4]
I've upgraded the module on XOOPS to the latest version and when I went to the module front end, I've got this:
![image](https://user-images.githubusercontent.com/613686/100467246-25ae1b80-30a0-11eb-8367-67452c6dabae.png)

So I went to Settings in Admin and have a request here:
![image](https://user-images.githubusercontent.com/613686/100468384-51320580-30a2-11eb-98d1-f3b07db61318.png)

But as XOOPS we don't have a token, so somebody would have to create and add their personal token, which is not good. 

What other programs do is to ask the user to add a token to their personal account, see: https://kamranahmed.info/githunt/, and then points to the place where the user can add the token to his personal account:
![image](https://user-images.githubusercontent.com/613686/100468639-d0273e00-30a2-11eb-8834-a4ae9c962039.png)

**Comment by ggoffy** [comment]
solved with last version
