### ISSUE TITLE
changelog.txt implemented ?

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#44]
Hi ! 
For the next version,
What about the Opportunity to add the /docs/changelog.txt in the page.

_Readme_ is displayed,
Why not _changelog.txt_ ?
It delivers lot of informations about the life of the module.

**Comment by ggoffy** [comment]
hi. the idea is to offer non experienced users 

- a quick overview about the existing modules and the functionalities/features of them
- a direct download for testing purposes

as experienced user you are interested in such details in changelog, of course, but this was not the goal of the module. And I would not overload it, lets keep it simple.

**Comment by alain01** [comment]
Ok,
Thanks for the clear anwser.

**Comment by ggoffy** [comment]
I have to say thank you for your thoughts :)
