### ISSUE TITLE
Missed Icons on the result search page

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#45]
I get this issue on my site and same problem on the amazing site myxoops.org ;-)

![Capture d’écran 2021-04-29 100226](https://user-images.githubusercontent.com/5336960/116519961-67065980-a8d2-11eb-8a3c-8b18dd49f5ef.png)

Wrong url source for the icon
> https://www.myxoops.org/modules/wggithub/assets/icons/16/repositories.png

it should be 

> /assets/icons/16/github.png

**Comment by ggoffy** [comment]
fixed with https://github.com/XoopsModules25x/wggithub/pull/46

many thanks
