### ISSUE TITLE
Settings error

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/wggithub#48]
Hi Goffy,

in my production site web, i have a problem now with the settings : 

Settings tab / Button "test settings" on my account (github account)

> A problem has occurred on our server!
> Page is currently unavailable
> We are working on a fix
> Please come back soon ...
> 
> Error : Error: Class 'XoopsModules\Wggithub\Github\RateLimitExceedException' not found

> Erreurs
> --
> Erreur: Error: Class 'XoopsModules/Wggithub/Github/RateLimitExceedException' not found dans le fichier /modules/wggithub/class/Github/Api.php ligne 302

I've changed my personal access token (asked by github).
The new one and the old token made same page !

It worked before. 
Is it cause Gihtub use new type of token ?

**Comment by alain01** [comment]
From Github : 

> We recently updated the format of our API authentication tokens, providing additional security benefits to all our customers.

**Comment by ggoffy** [comment]
hi Alain, I will check it

**Comment by ggoffy** [comment]
Hi. I have updated also my PAT, and changed settings in wgGithub with new key, and all is working.
did you update your key and enter new one in wgGithub?

**Comment by alain01** [comment]
I think so, I did,
I will redo ...

**Comment by alain01** [comment]
Ok, I just generated a new token, and I have the same problem

**Comment by alain01** [comment]
> Hey alain01!
> 
> A personal access token (XOOPS wgGithub token v3) with admin:org, repo, user, workflow, and write:packages scopes was recently added to your account. Visit https://github.com/settings/tokens for more information.
>

**Comment by ggoffy** [comment]
two points:
1) Error "RateLimitExceedException" means that you have exceeded max of 60 requests per hour (and each request of a repo or a readme is a new request)
2) testApi1 is testing public repos, and for public repos you do not need valid PAT
if you download current version there is a new extended test in, which is testing your primary setting and it should look like this:
![grafik](https://user-images.githubusercontent.com/7547661/131212290-cfa0fd91-d126-40ec-bfac-aa3b7e0c79c4.png)

can you please retest and report the error message

**Comment by alain01** [comment]
New wggithub version 
New PAT, 
and when I launch "Test setting": ... same...

Erreur: Error: Class 'XoopsModules/Wggithub/Github/RateLimitExceedException' not found dans le fichier /modules/wggithub/class/Github/Api.php ligne 302

**Comment by ggoffy** [comment]
user "goffy" registered

**Comment by alain01** [comment]
ok, seen with you.
Again the same problem with the lastest version but I can add repository, it is essential.
