### ISSUE TITLE
wrong quotation marks

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/wggithub#71]
When we have:

`src='<{xoAdminIcons home.png}>'`

it converts to:

`src='<{xoAdminIcons 'home.png'}>'`

while it should be:

`src="<{xoAdminIcons 'home.png'}>"`

or 

src='<{xoAdminIcons "home.png"}>'

**Comment by ggoffy** [comment]
I think this issue belongs to wgtestui ;)
I made a fix there
it should be now always "<{xoAdminIcons 'home.png'}>"

**Comment by mambax7** [comment]
sorry for posting in the wrong module!
